//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketStumblerFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreference
    {
        public string UserID { get; set; }
        public Nullable<bool> Consumer { get; set; }
        public Nullable<bool> Finance { get; set; }
        public Nullable<bool> Manufacturing { get; set; }
        public Nullable<bool> Food { get; set; }
        public Nullable<bool> Transportation { get; set; }
        public Nullable<bool> Automotive { get; set; }
        public Nullable<bool> Technology { get; set; }
        public Nullable<bool> Medical { get; set; }
        public Nullable<bool> PreciousMetals { get; set; }
        public Nullable<bool> Services { get; set; }
    }
}
